### ISSUE TITLE
Replace Azure Java SDK by REST

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-azure#10]
This can be used to retrieve Azure VM Information.
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get#virtualmachine

Java SDK introduces lots of dependency which makes containerized apps bigger and manual deployment harder...

related: https://github.com/hazelcast/hazelcast-azure/issues/8

**Comment by gokhanoner** [comment]
@mesutcelik it seems Azure doesn't give you a single REST AP to get all necessary information to verify if that VM matches the criteria. We need to call multiple REST endpoints. Here's a blog post that shows how many REST calls needed to get all necessary info: https://blogs.technet.microsoft.com/drew/2017/09/12/azure-rest-api-get-azurerm-virtual-machine-status/

**Comment by alparslanavci** [comment]
@gokhanoner yes, you are right. We have to make multiple calls to get the required information. I will try to implement something similar to GCP discovery mechanism.

**Comment by gokhanoner** [comment]
@alparslanavci I already implemented some of this some time ago, I'll try to update it with the latest changes & create a PR soon.

**Comment by alparslanavci** [comment]
@gokhanoner yes, Rafal shared me your branch. I checked it in general, and it implements most of the requirements we want. Just if you can add some tests, it will be great. Looking forward to see your PR! Thanks man!
