### ISSUE TITLE
Add support for virtual machine scale sets

### ISSUE THREAD

**Issue by justinskariah** [hazelcast/hazelcast-azure#11]
#### Current behaviour
The `hazelcast-azure` discovery plugin doesn't discover virtual machines if they are in a scale set. Current implementation uses `VirtualMachineOperations.list(resourceGroupName)` to list the VMs, this intern calls `https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines` which doesn't return virtual machines in a scale set.

#### Expected behaviour
The discovery plugin in addition to using `VirtualMachineOperations.list(resourceGroupName)` should also iterate through all the scale sets and list there VMs.

**Comment by mesutcelik** [comment]
Hi @justinskariah ,

Did you try to create availability set under the resource group?

```
az vm availability-set create --resource-group hazelcast-resource-group --name hazelcast-availability-set --platform-fault-domain-count 2 --platform-update-domain-count 2
```

**Comment by justinskariah** [comment]
Yes, I have created the scale set under a resource group, which I specified with `group-name`.

**Comment by mesutcelik** [comment]
hmm then it is weird because I have a working env right now with Availability Set.. 

is it working without Availability set? Are you tagging VMs correctly? Currently value part of the tag must be the port. Can you also send your hazelcast configuration?

setting ids in discovery configuration can be tricky so you need to make sure all subs-id,tenant-id etc. correctly configured.

**Comment by justinskariah** [comment]
Hi @mesutcelik , I think it would work for Avalibility Set, but I am trying to get it working for Virtual machine **Scale Set**. Have you tried this plugin with a Scale set?

**Comment by mesutcelik** [comment]
Ahh sorry. I misread what you have written. I am not sure if `Scale Set` works with the current plugin.  I will check it when I have time.

**Comment by mesutcelik** [comment]
Hi @justinskariah ,

I verified that does not work as you described so I am leaving the issue open. Any contribution is very welcome!

Have you tried hazelcast helm chart for easy scaling or kubernetes is not an option for you? AKS is already Generally Available so you can give it a shot too..
https://github.com/helm/charts/tree/master/stable/hazelcast

**Comment by justinskariah** [comment]
Thanks for verifying it @mesutcelik. Kubernetes is not an option for us. I did look at implementing scale set support for the azure plugin. To do that I need to first upgrade `azure-sdk` to the latest version and then add scale set support. Please let me know if I am on the correct track.

**Comment by mesutcelik** [comment]
We are actually planning to use REST based solution for zero dependency in hazelcast-azure. 
please see https://github.com/hazelcast/hazelcast-azure/issues/10

Therefore, it would be great if you can replace SDK completely by REST Calls.
@leszko has already implemented similar functionality for GCP Support so he can give some hints on how to do that...

Discovery in a Scale Set requires private IPs of VMs,I see that following command returns private IPs of a Scale Set.
```
$az vmss nic list -g hazelcast-resource-group --vmss-name hazelcast-scale-set --query [].{ip:ipConfigurations[0].privateIpAddress} -o tsv
10.0.0.6
10.0.0.7
```

And if you run that command with `--debug`, you can see the REST API call that is used is 
```
https://management.azure.com/subscriptions/${subs_id}/resourceGroups/${resource-group-name}/providers/microsoft.Compute/virtualMachineScaleSets/${scale-set-name}/networkInterfaces?api-version=2017-03-30
```

**Comment by gokhanoner** [comment]
@justinskariah I'm creating a PR to use REST API instead of SKD & will add support for scale set as well.
