### ISSUE TITLE
Built-in Member Address Provider SPI implementation

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast-azure#24]
Hazelcast IMDG members requires to configure `public-address` property when they are used with public IPs. Instead of configuring this property, we can provide an implementation of the `com.hazelcast.spi.MemberAddressProvider` interface which provides the bind and public address. See the details here: https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#member-address-provides-spi

**Note:** In Azure environment, only public IP addresses with basic SKU are available when using instance metadata service. Standard SKU is not supported as the time of writing this issue. See this link: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ip-addresses-overview-arm#standard

**Comment by peterjot** [comment]
I'd like to take it!

**Comment by Holmistr** [comment]
Hi @peterjot , I assigned you the issue! Thank you very much for the continuous effort. Good luck!
