### ISSUE TITLE
support for azure sdk 1.0.0-beta5

### ISSUE THREAD

**Issue by b-liberman** [hazelcast/hazelcast-azure#8]
Hi,
I would like to propose a change to support the latest azure sdk version. Unfortunately I was not able to create a new pull request. Attached is the code.
Regards

Boris

[AzureDiscoveryStrategy.zip](https://github.com/hazelcast/hazelcast-azure/files/857620/AzureDiscoveryStrategy.zip)

**Comment by mesutcelik** [comment]
Azure SDK has been updated to 1.14 as of hazelcast-azure-1.2.2 release.
